### ISSUE TITLE
[SKiDL BUG] netlist_to_skidl is no more?

### ISSUE THREAD

**Issue by cyberhuman** [devbisme/skidl#193]
**Describe the bug**

The documentation mentions the `netlist_to_skidl` tool under the section [Converting Existing Designs to SKiDL](https://devbisme.github.io/skidl/#converting-existing-designs-to-skidl).
However, some files are missing and the tool doesn't work.

**To Reproduce**
1. run `netlist_to_skidl -i sch.net -o sch.py -w`
2. observe the error:
```
Traceback (most recent call last):
  File "/home/alice/.conda/envs/bob/bin/netlist_to_skidl", line 5, in <module>
    from skidl.scripts.netlist_to_skidl_main import main
ModuleNotFoundError: No module named 'skidl.scripts'
```

**Expected behavior**
Either the shell script and the documentation should be removed, or the `netlist_to_skidl_main` should work.

**Comment by devbisme** [comment]
I restructured things a few months ago to remove the wildcard imports and that seems to be the cause of this problem. I pushed the fixes into the development branch.

**Comment by cyberhuman** [comment]
It works great now, thank you for the amazing software!
